import { useEffect, useState } from 'react'
import { RefreshCcw } from 'lucide-react'
import { customerApi } from '../api/customer'
const money = (v) => Number(v || 0).toLocaleString('ko-KR')
export default function RefundsPage() {
  const [items, setItems] = useState([]); const [orders, setOrders] = useState([]); const [orderId, setOrderId] = useState(''); const [reason, setReason] = useState(''); const [selected, setSelected] = useState({}); const [detail, setDetail] = useState(null); const [policy, setPolicy] = useState(null); const [error, setError] = useState('')
  const load = () => customerApi.getRefunds().then((d) => setItems(d.items || [])).catch((e) => setError(e.message))
  useEffect(() => { load(); customerApi.getOrders({ size: 100 }).then((d) => setOrders(d.items || [])).catch(() => {}) }, [])
  useEffect(() => { if (!orderId) { setDetail(null); setPolicy(null); return } customerApi.getOrder(orderId).then(setDetail).catch(() => setDetail(null)); customerApi.getRefundPolicy(orderId).then(setPolicy).catch(() => setPolicy(null)) }, [orderId])
  const submit = async (e) => { e.preventDefault(); const refundItems = Object.entries(selected).filter(([, q]) => Number(q) > 0).map(([id, q]) => ({ order_item_id: Number(id), refund_quantity: Number(q) })); if (!refundItems.length) return setError('환불할 상품 수량을 선택해주세요.'); try { await customerApi.createRefund({ order_id: Number(orderId), refund_reason: reason, items: refundItems }); setReason(''); setSelected({}); load() } catch (e) { setError(e.message) } }
  return <div className="container page-section"><div className="page-title"><span>REFUND</span><h1>취소/환불</h1><p>구매한 상품의 환불을 요청하고 처리 상태를 확인하세요.</p></div>{error && <div className="notice error">{error}</div>}
    <form className="panel refund-form" onSubmit={submit}><h3><RefreshCcw /> 환불 요청</h3><label>주문 선택<select value={orderId} onChange={(e) => setOrderId(e.target.value)} required><option value="">주문을 선택하세요</option>{orders.map((o) => <option key={o.order_id} value={o.order_id}>{o.order_no} · {o.order_status} · {money(o.total_amount)}원</option>)}</select></label>{policy && <div className="policy-mini"><b>{policy.policy_name}</b><span>환불 가능 기간: {policy.allowed_days}일 · 배송비 부담: {policy.shipping_fee_payer}</span></div>}{detail?.items?.map((i) => <div className="refund-item" key={i.order_item_id}><div><strong>{i.product_name_snapshot}</strong><span>구매수량 {i.quantity}개 · {money(i.item_amount)}원</span></div><input type="number" min="0" max={i.quantity} value={selected[i.order_item_id] || 0} onChange={(e) => setSelected({ ...selected, [i.order_item_id]: e.target.value })} /></div>)}<label>환불 사유<textarea value={reason} onChange={(e) => setReason(e.target.value)} required maxLength={500} rows={4} /></label><button className="btn btn-primary">환불 요청하기</button></form>
    <h2 className="subheading">내 환불 요청</h2><div className="refund-list">{items.map((r) => <article className="refund-card" key={r.refund_request_id}><div><strong>#{r.refund_request_id} · {r.order_no}</strong><span>{r.refund_reason || '환불 요청'}</span></div><div><span className="status-pill">{r.refund_status}</span><b>{money(r.requested_amount)}원</b></div></article>)}{!items.length && <div className="empty-box">환불 요청 내역이 없습니다.</div>}</div>
  </div>
}
